// <auto-generated />
using System;
using Expense.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Expense.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OutlayDbContext))]
    [Migration("20241129211218_Caterogiries_Table_Seed_Data")]
    partial class Caterogiries_Table_Seed_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Expense.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            CreatedAt = new DateTime(2024, 11, 29, 21, 12, 18, 433, DateTimeKind.Utc).AddTicks(2404),
                            Name = "Oziq-ovqat"
                        },
                        new
                        {
                            Id = 2m,
                            CreatedAt = new DateTime(2024, 11, 29, 21, 12, 18, 433, DateTimeKind.Utc).AddTicks(2407),
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 3m,
                            CreatedAt = new DateTime(2024, 11, 29, 21, 12, 18, 433, DateTimeKind.Utc).AddTicks(2408),
                            Name = "Mobil aloqa"
                        },
                        new
                        {
                            Id = 4m,
                            CreatedAt = new DateTime(2024, 11, 29, 21, 12, 18, 433, DateTimeKind.Utc).AddTicks(2410),
                            Name = "Internet"
                        },
                        new
                        {
                            Id = 5m,
                            CreatedAt = new DateTime(2024, 11, 29, 21, 12, 18, 433, DateTimeKind.Utc).AddTicks(2411),
                            Name = "O'yin-kulgi"
                        });
                });

            modelBuilder.Entity("Expense.Domain.Entities.Outlays.Outlay", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("CategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("outlays", (string)null);
                });

            modelBuilder.Entity("Expense.Domain.Entities.Outlays.Outlay", b =>
                {
                    b.HasOne("Expense.Domain.Entities.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
